name: Run Python Script

on:
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run Python Script
        run: |
          python -m pip install ultralytics
          python -m pip install telepot
          pip install pyqt5
          python a.py
      # - name: Run Python Script
      #   run: |
      #     python -m pip install pyTelegramBotAPI
      #     python a.py
org: home/runner/.cache/pip/wheels/ab/84/e4/5af8c76af9e5bee472e825f1451c18bb3b261d80a7b3ec7f8a
